file_name = "pahapakka.dek"
points = 80

# herjoja kortteja
[[boosters]]
set = "alpha"
amount = 0
price = 1.25

# herjoja kortteja
[[boosters]]
set = "beta"
amount = 0
price = 1.25

# herjoja kortteja
[[boosters]]
set = "unlimited"
amount = 0
price = 1.25

[[boosters]]
set = "an"
amount = 0
price = 1.0

[[boosters]]
set = "antiquities"
amount = 0
price = 1.0

[[boosters]]
set = "revised"
amount = 0
price = 1.25

# Hulluja moniväri ritareita ja muita legendoja
[[boosters]]
set = "legends"
amount = 0
price = 1.0

# gobliineja
[[boosters]]
set = "dark"
amount = 0
price = 1.0

[[boosters]]
set = "fe"
amount = 0
price = 1.0

[[boosters]]
set = "4e"
amount = 0
price = 0.75

[[boosters]]
set = "ia"
amount = 0
price = 0.75

# Sengir vampires
[[boosters]]
set = "homelands"
amount = 0
price = 1.0

[[boosters]]
set = "alliances"
amount = 0
price = 1.0

# Spirit of night, gobliineja, phasing
[[boosters]]
set = "mirage"
amount = 0
price = 1.0

# phyrexsian walker
[[boosters]]
set = "visions"
amount = 0
price = 1.0

[[boosters]]
set = "5e"
amount = 0
price = 0.75

[[boosters]]
set = "portal"
amount = 0
price = 1.0

[[boosters]]
set = "weatherlight"
amount = 0
price = 1.0

[[boosters]]
set = "tempest"
amount = 0
price = 1.25

[[boosters]]
set = "stronghold"
amount = 0
price = 1.25

[[boosters]]
set = "exodus"
amount = 0
price = 1.25

[[boosters]]
set = "6e"
amount = 0
price = 0.75

[[boosters]]
set = "7e"
amount = 0
price = 0.75

[[boosters]]
set = "portal2"
amount = 0
price = 1.25

[[boosters]]
set = "nemesis"
amount = 0
price = 1.25

# Planeswalkers fury!!!
[[boosters]]
set = "planeshift"
amount = 0
price = 1.25

[[boosters]]
set = "apocalypse"
amount = 0
price = 1.25

[[boosters]]
set = "odyssey"
amount = 0
price = 1.5

[[boosters]]
set = "uz"
amount = 0
price = 1.0

[[boosters]]
set = "ul"
amount = 0
price = 1.0

[[boosters]]
set = "ud"
amount = 0
price = 1.0

[[boosters]]
set = "mm"
amount = 0
price = 1.0

[[boosters]]
set = "prophecy"
amount = 0
price = 1.25

[[boosters]]
set = "invasion"
amount = 0
price = 1.25

[[boosters]]
set = "torment"
amount = 0
price = 1.5

[[boosters]]
set = "judgment"
amount = 0
price = 1.5

[[boosters]]
set = "onslaught"
amount = 0
price = 1.5